server:
  port: 8089

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: wowmin
    password: '!Dmssk6480'
    url: jdbc:mysql://mydb.cyqagiaocgni.ap-northeast-2.rds.amazonaws.com:33066/mydb

mybatis:
  config-location: classpath:/mybatis/config/config.xml
  mapper-locations: classpath:/mybatis/mapper/*.xml
